<?php
require_once 'config.php';

// This file handles QR code validation for tickets
// It's referenced in the QR codes generated by the system

try {
    // Get ticket ID from query parameter
    $ticketId = $_GET['id'] ?? null;
    
    if (!$ticketId) {
        http_response_code(400);
        echo json_encode(['error' => 'Ticket ID is required']);
        exit();
    }
    
    // Create database connection
    $pdo = createDatabaseConnection();
    
    // Check if ticket exists and get its details
    $stmt = $pdo->prepare("
        SELECT id, event_name, event_date, location, ticket_type, 
               price, custom_price, is_used, generated_at, qr_code
        FROM tickets 
        WHERE id = ?
    ");
    
    $stmt->execute([$ticketId]);
    $ticket = $stmt->fetch();
    
    if (!$ticket) {
        http_response_code(404);
        echo json_encode(['error' => 'Ticket not found']);
        exit();
    }
    
    // Return ticket validation information
    $response = [
        'success' => true,
        'ticket' => [
            'id' => $ticket['id'],
            'eventName' => $ticket['event_name'],
            'eventDate' => $ticket['event_date'],
            'location' => $ticket['location'],
            'ticketType' => $ticket['ticket_type'],
            'price' => $ticket['custom_price'] ?: $ticket['price'],
            'isUsed' => (bool)$ticket['is_used'],
            'generatedAt' => $ticket['generated_at'],
            'qrCode' => $ticket['qr_code']
        ]
    ];
    
    // If this is a validation request (not just info), mark as used
    if (isset($_POST['validate']) && $_POST['validate'] === 'true') {
        $updateStmt = $pdo->prepare("UPDATE tickets SET is_used = 1 WHERE id = ?");
        $updateStmt->execute([$ticketId]);
        $response['ticket']['isUsed'] = true;
        $response['message'] = 'Ticket validated successfully';
    }
    
    http_response_code(200);
    echo json_encode($response);
    
} catch (PDOException $e) {
    error_log("Database error in validate.php: " . $e->getMessage());
    http_response_code(500);
    echo json_encode(['error' => 'Database error: ' . $e->getMessage()]);
} catch (Exception $e) {
    error_log("General error in validate.php: " . $e->getMessage());
    http_response_code(500);
    echo json_encode(['error' => 'Server error: ' . $e->getMessage()]);
}
?>