<?php
require_once 'config.php';

// This file handles QR code validation for tickets
// It's referenced in the QR codes generated by the system

try {
    // Get user_id and event_id from query parameters
    $userId = $_GET['user_id'] ?? null;
    $eventId = $_GET['event_id'] ?? null;

    if (!$userId) {
        http_response_code(400);
        echo json_encode(['error' => 'User ID is required']);
        exit();
    }

    // Create database connection
    $pdo = createDatabaseConnection();

    // Check if ticket exists using user_id and optionally event_id
    if ($eventId) {
        // Search by both user_id and event_id for more specific match
        $stmt = $pdo->prepare("
            SELECT id, event_name, event_date, location, ticket_type,
                   price, custom_price, is_used, generated_at, qr_code, user_id, event_id
            FROM tickets
            WHERE user_id = ? AND event_id = ?
            ORDER BY generated_at DESC
            LIMIT 1
        ");
        $stmt->execute([$userId, $eventId]);
    } else {
        // Fallback: search by user_id only (get most recent ticket)
        $stmt = $pdo->prepare("
            SELECT id, event_name, event_date, location, ticket_type,
                   price, custom_price, is_used, generated_at, qr_code, user_id, event_id
            FROM tickets
            WHERE user_id = ?
            ORDER BY generated_at DESC
            LIMIT 1
        ");
        $stmt->execute([$userId]);
    }

    $ticket = $stmt->fetch();
    
    if (!$ticket) {
        http_response_code(404);
        echo json_encode(['error' => 'Ticket not found']);
        exit();
    }
    
    // Return ticket validation information
    $response = [
        'success' => true,
        'ticket' => [
            'id' => $ticket['id'],
            'eventName' => $ticket['event_name'],
            'eventDate' => $ticket['event_date'],
            'location' => $ticket['location'],
            'ticketType' => $ticket['ticket_type'],
            'price' => $ticket['custom_price'] ?: $ticket['price'],
            'isUsed' => (bool)$ticket['is_used'],
            'generatedAt' => $ticket['generated_at'],
            'qrCode' => $ticket['qr_code']
        ]
    ];
    
    // If this is a validation request (not just info), mark as used
    if (isset($_POST['validate']) && $_POST['validate'] === 'true') {
        $updateStmt = $pdo->prepare("UPDATE tickets SET is_used = 1 WHERE id = ?");
        $updateStmt->execute([$ticket['id']]);
        $response['ticket']['isUsed'] = true;
        $response['message'] = 'Ticket validated successfully';
    }
    
    http_response_code(200);
    echo json_encode($response);
    
} catch (PDOException $e) {
    error_log("Database error in validate.php: " . $e->getMessage());
    http_response_code(500);
    echo json_encode(['error' => 'Database error: ' . $e->getMessage()]);
} catch (Exception $e) {
    error_log("General error in validate.php: " . $e->getMessage());
    http_response_code(500);
    echo json_encode(['error' => 'Server error: ' . $e->getMessage()]);
}
?>